name: zeitschatz
description: Familieninterne TAN-App fuer Aufgaben (ZeitSchatz)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  flutter_riverpod: ^2.5.1
  dio: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  camera: ^0.11.0+1
  intl: ^0.18.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
